# Book settings
title: Proyecto de autoreconstrucción
author: Antonio Otal Palacín
logo: irimed.png
copyright: ""  # Copyright year to be placed in the footer

html:
  extra_navbar: Parte de la línea de investigación del <a href="http://www.uv.es/radiofisica/index.html">IRIMED</a>  # Will be displayed underneath the left navbar.
  use_repository_button     : true  # Whether to add a link to your repository button

latex:
  latex_documents:
    targetname: book.tex
launch_buttons:
  binderhub_url: "https://mybinder.org"  # The URL for your BinderHub (e.g., https://mybinder.org)
  thebe:  true
repository:
  url                       : https://github.com/aotal/CervixAuto  # The URL to your book's repository
  branch                    : master  # Which branch of the repository should be used when creating links
sphinx:
  config:
    html_show_copyright: false
    language: es
    html_theme: sphinx_book_theme # Para que aparezca en castellano hay que usar el fork de mi cuenta de github
    html_theme_options:
      search_bar_text: Buscar en la página...
